apiVersion: apps/v1
kind: Deployment
metadata:
  name: persona-api-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: persona-api
    replicas: 3
    template:
      metadata:
        labels:
          app: persona-api
      spec:
        containers:
          - name: persona-api
            image:
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 1000m
                memory: 1.5Gi
              limits:
                memory: 1.5Gi
            env:
              - name: TZ
                value: "Asia/Seoul"
            ports:
              - name: http
                protocol: TCP
                containerPort: 8010
            livenessProbe:
              httpGet:
                path: /health
                port: 8010
              initialDelaySeconds: 60
              periodSeconds: 20
              timeoutSeconds: 10
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /health
                port: 8010
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: persona-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: persona-api
  ports:
    - name: service-http
      protocol: TCP
      port: 8010
      targetPort: http
